# Site settings
author: merry-ninja-5973
title: 
header-img: img/home-bg.png
email: miles.erickson@gmail.com
copyright_name: merry-ninja-5973
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mileserickson

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
