# Site settings
author: Miles Erickson
title: Miles Erickson
header-img: img/home-bg.png
email: miles.erickson@gmail.com
copyright_name: Miles Erickson
description: > # this means to ignore newlines until "baseurl:"
  Python, Data Science, Data Engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mileserickson

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
